//! The bit-field layout, differentially against the host's own C compiler.
//!
//! Bit-field placement is entirely implementation defined, so the only honest
//! way to check it is to ask the implementation this crate claims to agree
//! with. That is what this test does: a corpus of a couple of hundred
//! `struct`s and `union`s mixing bit-fields of every type and width with
//! ordinary members is translated *twice* — once by `cinrs` and once by `cc` —
//! and the two are compared on `sizeof`, `_Alignof`, `offsetof` of every
//! ordinary member, the bytes of the object after a value is stored into each
//! bit-field, and the value read back out of it.
//!
//! # How the two halves are kept identical
//!
//! The corpus is not written by hand and not written twice. It lives in
//! `tests/include/bitfields_corpus.h`, a plain C header that
//!
//! * this file's `c11!` block `#include`s, so `cinrs` compiles it, and
//! * the generated `main.c` `#include`s, so `cc` compiles it.
//!
//! The header also holds the *reporting* code — `bf_report`, which writes the
//! whole comparison into a caller-supplied buffer with `sprintf`. Both sides
//! therefore run the same C, and the test compares two strings; there is no
//! second implementation of the format to drift out of step.
//!
//! The header itself is generated by [`corpus`] below from a fixed seed, and is
//! committed so that the `c11!` block has something to read at compile time.
//! The test regenerates it and fails if what is on disk differs, so the two can
//! never disagree; `CINRS_BLESS_BITFIELD_CORPUS=1` rewrites it.
//!
//! # Skipping
//!
//! Without a C compiler on `PATH` there is nothing to compare against, and the
//! test prints why and passes. `CINRS_BITFIELD_CC` names the compiler, `CC` is
//! consulted next, and `cc` is the default.

use std::fmt::Write as _;
use std::path::{Path, PathBuf};
use std::process::Command;

use cinrs::c11;

c11! {
    #include "include/bitfields_corpus.h"
}

// The generated `check_generated_layout`, one assertion per record and per
// ordinary member; see `the_layout_cinrs_computed_is_the_one_rustc_gave`.
include!("include/bitfields_corpus_checks.rs");

// ---------------------------------------------------------------------------
// the corpus generator
// ---------------------------------------------------------------------------

/// The seed the corpus is generated from. Changing it changes the corpus, and
/// the committed header has to be blessed again.
const SEED: u64 = 0x000c_117b_17f1_e1d5;

/// How many records the corpus holds.
const RECORDS: usize = 200;

/// `splitmix64`, so that the corpus is the same everywhere and forever.
struct Rng(u64);

impl Rng {
    fn next(&mut self) -> u64 {
        self.0 = self.0.wrapping_add(0x9E37_79B9_7F4A_7C15);
        let mut z = self.0;
        z = (z ^ (z >> 30)).wrapping_mul(0xBF58_476D_1CE4_E5B9);
        z = (z ^ (z >> 27)).wrapping_mul(0x94D0_49BB_1331_11EB);
        z ^ (z >> 31)
    }

    /// A value in `0..n`.
    fn below(&mut self, n: usize) -> usize {
        (self.next() % n as u64) as usize
    }

    /// A value in `low..=high`.
    fn between(&mut self, low: u32, high: u32) -> u32 {
        low + (self.next() % u64::from(high - low + 1)) as u32
    }
}

/// The types a bit-field may have, and the widest field of each.
///
/// The widths of `long` stop at 32 so that the corpus is valid on a target
/// where `long` is 32 bits too; everything wider is covered by `long long`.
const BIT_TYPES: &[(&str, u32)] = &[
    ("_Bool", 1),
    ("char", 8),
    ("signed char", 8),
    ("unsigned char", 8),
    ("short", 16),
    ("unsigned short", 16),
    ("int", 32),
    ("unsigned int", 32),
    ("long", 32),
    ("unsigned long", 32),
    ("long long", 64),
    ("unsigned long long", 64),
    ("enum BfSigned", 32),
    // One bit short of `int`: an enumeration whose underlying type is
    // unsigned can hold a full-width value that `int` cannot represent, and
    // `cinrs` gives every enumeration the type `int`. See the crate docs.
    ("enum BfUnsigned", 31),
];

/// The types an ordinary member may have: the declaration's prefix, the
/// declarator's suffix, and whether a `long long` can be stored into it.
const PLAIN_TYPES: &[(&str, &str, bool)] = &[
    ("char", "", true),
    ("short", "", true),
    ("int", "", true),
    ("long long", "", true),
    ("double", "", false),
    ("void *", "", false),
    ("struct BfInner", "", false),
    ("struct BfNested", "", false),
    ("int", "[2]", false),
];

/// One member of a generated record.
struct Field {
    /// The member's declaration, without the trailing `;`.
    decl: String,
    /// The member's name, absent for an unnamed bit-field.
    name: Option<String>,
    /// The cast a probe stores through, absent when the member cannot hold a
    /// `long long`.
    store: Option<String>,
    /// Whether the member is a bit-field, which has no `offsetof`.
    bits: bool,
}

/// How a generated record is packed.
///
/// The three forms are not interchangeable: `__attribute__((packed))` caps
/// every member at one byte, `#pragma pack(N)` caps them at N — and switches
/// the bit-field allocation-unit rule off for the whole record either way —
/// while a `packed` on one *member* leaves the rest alone.
#[derive(Clone, Copy, PartialEq, Eq)]
enum Packing {
    /// Natural alignment throughout.
    None,
    /// `__attribute__((packed))` on the record.
    Attribute,
    /// `#pragma pack(N)` around the record.
    Pragma(u32),
    /// `__attribute__((packed))` on one member, chosen by index.
    Member(usize),
}

/// Everything the generator decided about one record beyond its members.
struct Shape {
    packing: Packing,
    /// `__attribute__((aligned(N)))` on the record, which never appears
    /// together with packing: Rust refuses `#[repr(C, packed, align(N))]`.
    aligned: Option<u32>,
    /// `__attribute__((aligned(N)))` on one ordinary member.
    member_aligned: Option<(usize, u32)>,
}

impl Shape {
    /// Whether the generated Rust item can carry the record's alignment.
    ///
    /// A record one *member* of which is packed cannot: Rust has no way to
    /// spell `packed` and `align(N)` at once, so the item is left one byte
    /// aligned while C keeps the alignment of its other members. Offsets and
    /// `sizeof` still agree, which is what the C program can observe.
    fn rust_carries_alignment(&self) -> bool {
        !matches!(self.packing, Packing::Member(_))
    }
}

/// The two generated files: the C corpus and the Rust assertions over it.
struct Corpus {
    header: String,
    checks: String,
}

/// Builds the corpus header and the Rust layout assertions that go with it.
fn corpus() -> Corpus {
    let mut rng = Rng(SEED);
    let mut out = String::new();
    out.push_str(HEADER_PROLOGUE);
    let mut checks = String::from(CHECKS_PROLOGUE);

    let mut queries = String::new();
    for index in 0..RECORDS {
        let tag = format!("S{index:03}");
        let union = rng.below(4) == 0;
        let mut fields = record_fields(&mut rng, union);
        let shape = record_shape(&mut rng, &fields);
        let keyword = if union { "union" } else { "struct" };

        // `packed` on one member, and `aligned(N)` on one, are written onto
        // the declaration rather than onto the record.
        if let Packing::Member(at) = shape.packing {
            fields[at].decl.push_str(" __attribute__((packed))");
        }
        if let Some((at, align)) = shape.member_aligned {
            let _ = write!(fields[at].decl, " __attribute__((aligned({align})))");
        }
        if let Packing::Pragma(n) = shape.packing {
            let _ = writeln!(out, "#pragma pack({n})");
        }
        let record_attrs = match (shape.packing, shape.aligned) {
            (Packing::Attribute, _) => " __attribute__((packed))".to_owned(),
            (_, Some(align)) => format!(" __attribute__((aligned({align})))"),
            _ => String::new(),
        };
        let _ = writeln!(out, "{keyword} {tag} {{");
        for field in &fields {
            let _ = writeln!(out, "    {};", field.decl);
        }
        let _ = writeln!(out, "}}{record_attrs};");
        if let Packing::Pragma(_) = shape.packing {
            let _ = writeln!(out, "#pragma pack()");
        }
        let _ = writeln!(out);

        let named: Vec<&Field> = fields.iter().filter(|f| f.name.is_some()).collect();
        let check = if shape.rust_carries_alignment() {
            "check_record"
        } else {
            "check_record_size_only"
        };
        let _ = writeln!(checks, "    {check}::<{tag}>({index}, \"{tag}\");");
        for (k, field) in named.iter().enumerate() {
            if field.bits {
                continue;
            }
            let name = field.name.as_deref().expect("named");
            let _ = writeln!(
                checks,
                "    check_offset({index}, {k}, ::core::mem::offset_of!({tag}, {name}), \
                 \"{tag}.{name}\");"
            );
        }
        let _ = writeln!(
            queries,
            "static long long bf_query_{index:03}(int op, int k, long long value, \
             unsigned char *out) {{"
        );
        let _ = writeln!(queries, "    {keyword} {tag} v;");
        let _ = writeln!(queries, "    unsigned char *p;");
        let _ = writeln!(queries, "    unsigned long i;");
        let _ = writeln!(
            queries,
            "    if (op == 0) return (long long) sizeof({keyword} {tag});"
        );
        let _ = writeln!(
            queries,
            "    if (op == 1) return (long long) _Alignof({keyword} {tag});"
        );
        let _ = writeln!(queries, "    if (op == 2) return {};", named.len());
        let _ = writeln!(queries, "    if (op == 3) {{");
        for (k, field) in named.iter().enumerate() {
            let name = field.name.as_deref().expect("named");
            if field.bits {
                let _ = writeln!(queries, "        if (k == {k}) return -1;");
            } else {
                let _ = writeln!(
                    queries,
                    "        if (k == {k}) return (long long) \
                     offsetof({keyword} {tag}, {name});"
                );
            }
        }
        let _ = writeln!(queries, "        return -1;");
        let _ = writeln!(queries, "    }}");
        let _ = writeln!(queries, "    p = (unsigned char *) &v;");
        let _ = writeln!(queries, "    for (i = 0; i < sizeof v; i++) p[i] = 0;");
        for (k, field) in named.iter().enumerate() {
            let name = field.name.as_deref().expect("named");
            if let Some(cast) = &field.store {
                let _ = writeln!(queries, "    if (k == {k}) v.{name} = ({cast}) value;");
            }
        }
        let _ = writeln!(queries, "    for (i = 0; i < sizeof v; i++) out[i] = p[i];");
        for (k, field) in named.iter().enumerate() {
            let name = field.name.as_deref().expect("named");
            if field.store.is_some() {
                let _ = writeln!(queries, "    if (k == {k}) return (long long) v.{name};");
            }
        }
        let _ = writeln!(queries, "    return 0;");
        let _ = writeln!(queries, "}}");
        let _ = writeln!(queries);
    }
    out.push_str(&queries);

    let _ = writeln!(
        out,
        "typedef long long (*BfQuery)(int, int, long long, unsigned char *);"
    );
    let _ = writeln!(out, "static BfQuery bf_queries[{RECORDS}] = {{");
    for index in 0..RECORDS {
        let _ = writeln!(out, "    bf_query_{index:03},");
    }
    let _ = writeln!(out, "}};");
    let _ = writeln!(out);
    out.push_str(HEADER_EPILOGUE);
    checks.push_str("}\n");
    Corpus {
        header: out,
        checks,
    }
}

/// How one record is packed and aligned.
///
/// Every form is generated, and never two that Rust cannot spell together:
/// `#[repr(C, packed, align(N))]` is `E0587`, so a record is either packed or
/// over-aligned. A `union` is left unpacked — every member is at offset zero
/// there, so packing has nothing to move and only the alignment would change.
fn record_shape(rng: &mut Rng, fields: &[Field]) -> Shape {
    let ordinary: Vec<usize> = fields
        .iter()
        .enumerate()
        .filter(|(_, f)| !f.bits && f.name.is_some())
        .map(|(i, _)| i)
        .collect();
    let packing = match rng.below(8) {
        0 => Packing::Attribute,
        1 => Packing::Pragma(1),
        2 => Packing::Pragma(2),
        3 => Packing::Pragma(4),
        4 if !ordinary.is_empty() => Packing::Member(ordinary[rng.below(ordinary.len())]),
        _ => Packing::None,
    };
    let aligned = if packing == Packing::None && rng.below(6) == 0 {
        Some(1u32 << rng.between(3, 5))
    } else {
        None
    };
    // An `aligned` member only ever *raises* an alignment, so it is safe to
    // put on any ordinary member of a record that is not packed.
    let member_aligned = match (&packing, ordinary.is_empty()) {
        (Packing::None, false) if rng.below(6) == 0 => Some((
            ordinary[rng.below(ordinary.len())],
            1u32 << rng.between(3, 4),
        )),
        _ => None,
    };
    Shape {
        packing,
        aligned,
        member_aligned,
    }
}

/// The members of one record.
fn record_fields(rng: &mut Rng, union: bool) -> Vec<Field> {
    let count = rng.between(2, 6) as usize;
    let mut fields = Vec::with_capacity(count);
    let mut named = 0usize;
    for index in 0..count {
        // Three members in four are bit-fields, and one bit-field in five is
        // unnamed — which is where the zero-width form lives.
        let plain = rng.below(4) == 0;
        if plain {
            let (prefix, suffix, settable) = PLAIN_TYPES[rng.below(PLAIN_TYPES.len())];
            let name = format!("f{index}");
            fields.push(Field {
                decl: format!("{prefix} {name}{suffix}"),
                store: settable.then(|| prefix.to_owned()),
                name: Some(name),
                bits: false,
            });
            named += 1;
            continue;
        }
        let (ty, limit) = BIT_TYPES[rng.below(BIT_TYPES.len())];
        // An unnamed bit-field is the only one that may be zero width, and a
        // zero-width one in a union would be a member that is not there at all.
        let anonymous = rng.below(5) == 0;
        if anonymous {
            let width = if union { 1 } else { 0 };
            let width = if rng.below(2) == 0 {
                width
            } else {
                rng.between(1, limit)
            };
            fields.push(Field {
                decl: format!("{ty} : {width}"),
                name: None,
                store: None,
                bits: true,
            });
            continue;
        }
        let width = rng.between(1, limit);
        let name = format!("f{index}");
        fields.push(Field {
            decl: format!("{ty} {name} : {width}"),
            store: Some(ty.to_owned()),
            name: Some(name),
            bits: true,
        });
        named += 1;
    }
    if named == 0 {
        // Every record needs a member something can be stored into, and C
        // needs one that is not an unnamed bit-field.
        fields.push(Field {
            decl: "int f9 : 5".to_owned(),
            name: Some("f9".to_owned()),
            store: Some("int".to_owned()),
            bits: true,
        });
    }
    fields
}

/// What every generated corpus starts with.
const HEADER_PROLOGUE: &str = r#"/* The bit-field corpus, generated by tests/bitfield_layout.rs.
 *
 * Do not edit: regenerate it with
 *
 *     CINRS_BLESS_BITFIELD_CORPUS=1 cargo test --test bitfield_layout
 *
 * It is included both by that test's `c11!` block and by the `main.c` the test
 * hands to the host C compiler, so that the two sides compile the same text.
 */
#ifndef CINRS_BITFIELDS_CORPUS_H
#define CINRS_BITFIELDS_CORPUS_H

#include <stddef.h>
#include <stdio.h>

/* An enumeration with a negative enumerator, whose underlying type is
 * therefore signed, and one without, which GCC and Clang make unsigned. */
enum BfSigned { BFS_NEG = -1, BFS_ZERO = 0, BFS_BIG = 200 };
enum BfUnsigned { BFU_A = 0, BFU_B = 148, BFU_C = 149 };

/* Ordinary records a corpus member may have as its type; the second has
 * bit-fields of its own, so that a nested one is covered too. */
struct BfInner { int a; char b; };
struct BfNested { unsigned int p : 3; int q : 5; char r; };

"#;

/// What every generated corpus ends with: the report both sides print.
const HEADER_EPILOGUE: &str = r#"static const long long bf_values[5] = {
    0, -1, 1, 6148914691236517205LL, -6148914691236517206LL
};

int bf_count(void) { return (int) (sizeof bf_queries / sizeof bf_queries[0]); }

long long bf_query(int s, int op, int k, long long value, unsigned char *out) {
    return bf_queries[s](op, k, value, out);
}

/* Writes the whole comparison into `out` and returns its length.
 *
 * Both halves of the differential test call this, so the format cannot drift
 * between them.
 */
long bf_report(char *out) {
    char *w = out;
    int s, k, vi;
    unsigned long i;
    long long size, align, members, offset, got;
    unsigned char bytes[256];
    for (s = 0; s < bf_count(); s++) {
        size = bf_query(s, 0, 0, 0, bytes);
        align = bf_query(s, 1, 0, 0, bytes);
        members = bf_query(s, 2, 0, 0, bytes);
        w += sprintf(w, "S%03d size=%lld align=%lld members=%lld\n",
                     s, size, align, members);
        for (k = 0; k < (int) members; k++) {
            offset = bf_query(s, 3, k, 0, bytes);
            w += sprintf(w, "S%03d f%d offset=%lld\n", s, k, offset);
            for (vi = 0; vi < 5; vi++) {
                got = bf_query(s, 4, k, bf_values[vi], bytes);
                w += sprintf(w, "S%03d f%d v%d read=%lld bytes=", s, k, vi, got);
                for (i = 0; i < (unsigned long) size; i++) {
                    w += sprintf(w, "%02x", bytes[i]);
                }
                w += sprintf(w, "\n");
            }
        }
    }
    return (long) (w - out);
}

#endif /* CINRS_BITFIELDS_CORPUS_H */
"#;

/// What the generated Rust assertions start with.
const CHECKS_PROLOGUE: &str = "\
// The layout assertions over the bit-field corpus, generated by
// tests/bitfield_layout.rs alongside include/bitfields_corpus.h.
//
// Do not edit: regenerate both with
//
//     CINRS_BLESS_BITFIELD_CORPUS=1 cargo test --test bitfield_layout
//
// It is `include!`d by that test, which defines `check_record` and
// `check_offset`.
fn check_generated_layout() {
";

/// The `main` handed to the host compiler.
const MAIN_C: &str = r#"#include <stdio.h>
#include "bitfields_corpus.h"

static char buffer[1 << 23];

int main(void) {
    long n = bf_report(buffer);
    fwrite(buffer, 1, (size_t) n, stdout);
    return 0;
}
"#;

// ---------------------------------------------------------------------------
// the test
// ---------------------------------------------------------------------------

fn manifest_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
}

fn corpus_path() -> PathBuf {
    manifest_dir().join("tests/include/bitfields_corpus.h")
}

fn checks_path() -> PathBuf {
    manifest_dir().join("tests/include/bitfields_corpus_checks.rs")
}

/// The compiler to compare against, if there is one.
fn c_compiler() -> Option<String> {
    let named = std::env::var("CINRS_BITFIELD_CC")
        .or_else(|_| std::env::var("CC"))
        .unwrap_or_else(|_| "cc".to_owned());
    let ok = Command::new(&named)
        .arg("--version")
        .output()
        .is_ok_and(|out| out.status.success());
    ok.then_some(named)
}

#[test]
fn the_committed_corpus_is_what_the_generator_produces() {
    let generated = corpus();
    let files = [
        (corpus_path(), generated.header),
        (checks_path(), generated.checks),
    ];
    let bless = std::env::var_os("CINRS_BLESS_BITFIELD_CORPUS").is_some();
    for (path, wanted) in files {
        if bless {
            std::fs::write(&path, &wanted).expect("the corpus directory must be writable");
            continue;
        }
        let on_disk = std::fs::read_to_string(&path).expect("the corpus must be checked in");
        assert!(
            on_disk == wanted,
            "{} is not what the generator in this file produces; regenerate it with\n    \
             CINRS_BLESS_BITFIELD_CORPUS=1 cargo test --test bitfield_layout",
            path.display()
        );
    }
}

/// The size and alignment `cinrs` folded into the generated code have to be
/// the ones `rustc` gave the items it generated, or `sizeof` inside the C is a
/// different number from the object the C runs on.
#[test]
fn the_layout_cinrs_computed_is_the_one_rustc_gave() {
    check_generated_layout();
}

/// One record: what the C thinks its size and alignment are against what the
/// Rust item really has.
fn check_record<T>(index: usize, name: &str) {
    let index = index as ::core::ffi::c_int;
    let null = ::core::ptr::null_mut();
    let size = unsafe { bf_query(index, 0, 0, 0, null) };
    let align = unsafe { bf_query(index, 1, 0, 0, null) };
    assert_eq!(size as usize, size_of::<T>(), "sizeof {name}");
    assert_eq!(align as usize, align_of::<T>(), "_Alignof {name}");
}

/// The same, for a record whose Rust item cannot carry the alignment.
///
/// One member packed and the rest not is the only shape where the two differ:
/// Rust refuses `#[repr(C, packed, align(N))]`, so the item is one byte
/// aligned. What the C program can observe — every offset, and `sizeof` — is
/// still identical, and the alignment the item does have must at least divide
/// the one C computed, or an array of them would stride differently.
fn check_record_size_only<T>(index: usize, name: &str) {
    let index = index as ::core::ffi::c_int;
    let null = ::core::ptr::null_mut();
    let size = unsafe { bf_query(index, 0, 0, 0, null) };
    let align = unsafe { bf_query(index, 1, 0, 0, null) };
    assert_eq!(size as usize, size_of::<T>(), "sizeof {name}");
    assert!(
        (align as usize).is_multiple_of(align_of::<T>()),
        "_Alignof {name}: the item's {} does not divide C's {align}",
        align_of::<T>()
    );
}

/// One ordinary member: `offsetof` against `offset_of!`.
fn check_offset(index: usize, member: usize, actual: usize, name: &str) {
    let null = ::core::ptr::null_mut();
    let want = unsafe {
        bf_query(
            index as ::core::ffi::c_int,
            3,
            member as ::core::ffi::c_int,
            0,
            null,
        )
    };
    assert_eq!(want as usize, actual, "offsetof {name}");
}

#[test]
fn the_layout_agrees_with_the_host_c_compiler() {
    let Some(cc) = c_compiler() else {
        println!(
            "skipping: no C compiler on PATH (set CINRS_BITFIELD_CC or CC to name one), \
             so there is nothing to compare the bit-field layout against"
        );
        return;
    };

    let ours = report_through_cinrs();
    let theirs = report_through(&cc);
    if ours == theirs {
        return;
    }
    let mismatch = ours
        .lines()
        .zip(theirs.lines())
        .find(|(a, b)| a != b)
        .map(|(a, b)| format!("cinrs: {a}\n   {cc}: {b}"))
        .unwrap_or_else(|| {
            format!(
                "the reports have different lengths: {} lines from cinrs, {} from {cc}",
                ours.lines().count(),
                theirs.lines().count()
            )
        });
    panic!("the bit-field layout differs from {cc}'s:\n{mismatch}");
}

/// The report as the translated corpus produces it.
fn report_through_cinrs() -> String {
    // Large enough for the whole corpus; the C side uses the same bound.
    let mut buffer = vec![0u8; 1 << 23];
    let written = unsafe { bf_report(buffer.as_mut_ptr().cast()) };
    let len = usize::try_from(written).expect("the report cannot be negative");
    assert!(len < buffer.len(), "the report buffer was too small");
    String::from_utf8(buffer[..len].to_vec()).expect("the report is ASCII")
}

/// The report as the host compiler produces it.
fn report_through(cc: &str) -> String {
    let dir = manifest_dir().join("target/bitfield-layout");
    std::fs::create_dir_all(&dir).expect("target/ must be writable");
    let source = dir.join("main.c");
    std::fs::write(&source, MAIN_C).expect("target/ must be writable");
    let binary = dir.join("corpus_report");

    let include = corpus_path()
        .parent()
        .expect("the corpus has a directory")
        .to_path_buf();
    let output = Command::new(cc)
        .args(["-std=c11", "-w", "-O0"])
        .arg("-I")
        .arg(&include)
        .arg(&source)
        .arg("-o")
        .arg(&binary)
        .output()
        .unwrap_or_else(|e| panic!("could not run {cc}: {e}"));
    assert!(
        output.status.success(),
        "{cc} could not compile the corpus:\n{}",
        String::from_utf8_lossy(&output.stderr)
    );
    run(&binary)
}

fn run(binary: &Path) -> String {
    let output = Command::new(binary)
        .output()
        .unwrap_or_else(|e| panic!("could not run {}: {e}", binary.display()));
    assert!(
        output.status.success(),
        "{} exited with {}",
        binary.display(),
        output.status
    );
    String::from_utf8(output.stdout).expect("the report is ASCII")
}
