//! The x86 intrinsics `cinrs` maps onto `core::arch`, by name.
//!
//! **Generated** by `crates/cinrs-core/tests/x86_intrinsics.rs` from the
//! `stdarch` source the standard library is built from; do not edit. The
//! bundled `<immintrin.h>` and its companions declare exactly these names,
//! and the same generator writes both, so a prototype and its mapping cannot
//! disagree.
//!
//! Sorted by name: [`super::lookup`] is a binary search.

use super::{Imm, Intrinsic};

/// Every intrinsic this crate knows, sorted by name.
///
/// One line per entry, which `rustfmt` would otherwise turn into six
/// thousand: the table is read as a table, and `header_and_table_agree`
/// parses these lines.
#[rustfmt::skip]
pub(super) static INTRINSICS: &[Intrinsic] = &[
    Intrinsic { name: "_andn_u32", feature: "bmi1", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_andn_u64", feature: "bmi1", arity: 2, imm: &[], x86_64_only: true },
    Intrinsic { name: "_bextr2_u32", feature: "bmi1", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_bextr2_u64", feature: "bmi1", arity: 2, imm: &[], x86_64_only: true },
    Intrinsic { name: "_bextr_u32", feature: "bmi1", arity: 3, imm: &[], x86_64_only: false },
    Intrinsic { name: "_bextr_u64", feature: "bmi1", arity: 3, imm: &[], x86_64_only: true },
    Intrinsic { name: "_blsi_u32", feature: "bmi1", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_blsi_u64", feature: "bmi1", arity: 1, imm: &[], x86_64_only: true },
    Intrinsic { name: "_blsmsk_u32", feature: "bmi1", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_blsmsk_u64", feature: "bmi1", arity: 1, imm: &[], x86_64_only: true },
    Intrinsic { name: "_blsr_u32", feature: "bmi1", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_blsr_u64", feature: "bmi1", arity: 1, imm: &[], x86_64_only: true },
    Intrinsic { name: "_bzhi_u32", feature: "bmi2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_bzhi_u64", feature: "bmi2", arity: 2, imm: &[], x86_64_only: true },
    Intrinsic { name: "_lzcnt_u32", feature: "lzcnt", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_lzcnt_u64", feature: "lzcnt", arity: 1, imm: &[], x86_64_only: true },
    Intrinsic { name: "_mm256_abs_epi16", feature: "avx2", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_abs_epi32", feature: "avx2", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_abs_epi8", feature: "avx2", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_add_epi16", feature: "avx2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_add_epi32", feature: "avx2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_add_epi64", feature: "avx2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_add_epi8", feature: "avx2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_add_pd", feature: "avx", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_add_ps", feature: "avx", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_adds_epi16", feature: "avx2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_adds_epi8", feature: "avx2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_adds_epu16", feature: "avx2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_adds_epu8", feature: "avx2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_addsub_pd", feature: "avx", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_addsub_ps", feature: "avx", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_alignr_epi8", feature: "avx2", arity: 3, imm: &[Imm { index: 2, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm256_and_pd", feature: "avx", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_and_ps", feature: "avx", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_and_si256", feature: "avx2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_andnot_pd", feature: "avx", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_andnot_ps", feature: "avx", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_andnot_si256", feature: "avx2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_avg_epu16", feature: "avx2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_avg_epu8", feature: "avx2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_blend_epi16", feature: "avx2", arity: 3, imm: &[Imm { index: 2, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm256_blend_epi32", feature: "avx2", arity: 3, imm: &[Imm { index: 2, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm256_blend_pd", feature: "avx", arity: 3, imm: &[Imm { index: 2, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm256_blend_ps", feature: "avx", arity: 3, imm: &[Imm { index: 2, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm256_blendv_epi8", feature: "avx2", arity: 3, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_blendv_pd", feature: "avx", arity: 3, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_blendv_ps", feature: "avx", arity: 3, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_broadcastb_epi8", feature: "avx2", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_broadcastd_epi32", feature: "avx2", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_broadcastq_epi64", feature: "avx2", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_broadcastsd_pd", feature: "avx2", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_broadcastsi128_si256", feature: "avx2", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_broadcastss_ps", feature: "avx2", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_broadcastw_epi16", feature: "avx2", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_bslli_epi128", feature: "avx2", arity: 2, imm: &[Imm { index: 1, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm256_bsrli_epi128", feature: "avx2", arity: 2, imm: &[Imm { index: 1, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm256_castpd128_pd256", feature: "avx", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_castpd256_pd128", feature: "avx", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_castpd_ps", feature: "avx", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_castpd_si256", feature: "avx", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_castps128_ps256", feature: "avx", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_castps256_ps128", feature: "avx", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_castps_pd", feature: "avx", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_castps_si256", feature: "avx", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_castsi128_si256", feature: "avx", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_castsi256_pd", feature: "avx", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_castsi256_ps", feature: "avx", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_castsi256_si128", feature: "avx", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_ceil_pd", feature: "avx", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_ceil_ps", feature: "avx", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_cmp_pd", feature: "avx", arity: 3, imm: &[Imm { index: 2, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm256_cmp_ps", feature: "avx", arity: 3, imm: &[Imm { index: 2, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm256_cmpeq_epi16", feature: "avx2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_cmpeq_epi32", feature: "avx2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_cmpeq_epi64", feature: "avx2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_cmpeq_epi8", feature: "avx2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_cmpgt_epi16", feature: "avx2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_cmpgt_epi32", feature: "avx2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_cmpgt_epi64", feature: "avx2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_cmpgt_epi8", feature: "avx2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_cvtepi16_epi32", feature: "avx2", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_cvtepi16_epi64", feature: "avx2", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_cvtepi32_epi64", feature: "avx2", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_cvtepi32_pd", feature: "avx", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_cvtepi32_ps", feature: "avx", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_cvtepi8_epi16", feature: "avx2", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_cvtepi8_epi32", feature: "avx2", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_cvtepi8_epi64", feature: "avx2", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_cvtepu16_epi32", feature: "avx2", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_cvtepu16_epi64", feature: "avx2", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_cvtepu32_epi64", feature: "avx2", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_cvtepu8_epi16", feature: "avx2", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_cvtepu8_epi32", feature: "avx2", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_cvtepu8_epi64", feature: "avx2", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_cvtpd_epi32", feature: "avx", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_cvtpd_ps", feature: "avx", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_cvtps_epi32", feature: "avx", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_cvtps_pd", feature: "avx", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_cvtsd_f64", feature: "avx", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_cvtsi256_si32", feature: "avx", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_cvtss_f32", feature: "avx", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_cvttpd_epi32", feature: "avx", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_cvttps_epi32", feature: "avx", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_div_pd", feature: "avx", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_div_ps", feature: "avx", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_dp_ps", feature: "avx", arity: 3, imm: &[Imm { index: 2, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm256_extract_epi16", feature: "avx2", arity: 2, imm: &[Imm { index: 1, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm256_extract_epi32", feature: "avx", arity: 2, imm: &[Imm { index: 1, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm256_extract_epi64", feature: "avx", arity: 2, imm: &[Imm { index: 1, rust_ty: "i32" }], x86_64_only: true },
    Intrinsic { name: "_mm256_extract_epi8", feature: "avx2", arity: 2, imm: &[Imm { index: 1, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm256_extractf128_pd", feature: "avx", arity: 2, imm: &[Imm { index: 1, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm256_extractf128_ps", feature: "avx", arity: 2, imm: &[Imm { index: 1, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm256_extractf128_si256", feature: "avx", arity: 2, imm: &[Imm { index: 1, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm256_extracti128_si256", feature: "avx2", arity: 2, imm: &[Imm { index: 1, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm256_floor_pd", feature: "avx", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_floor_ps", feature: "avx", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_fmadd_pd", feature: "fma", arity: 3, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_fmadd_ps", feature: "fma", arity: 3, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_fmaddsub_pd", feature: "fma", arity: 3, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_fmaddsub_ps", feature: "fma", arity: 3, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_fmsub_pd", feature: "fma", arity: 3, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_fmsub_ps", feature: "fma", arity: 3, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_fmsubadd_pd", feature: "fma", arity: 3, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_fmsubadd_ps", feature: "fma", arity: 3, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_fnmadd_pd", feature: "fma", arity: 3, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_fnmadd_ps", feature: "fma", arity: 3, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_fnmsub_pd", feature: "fma", arity: 3, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_fnmsub_ps", feature: "fma", arity: 3, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_hadd_epi16", feature: "avx2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_hadd_epi32", feature: "avx2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_hadd_pd", feature: "avx", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_hadd_ps", feature: "avx", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_hadds_epi16", feature: "avx2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_hsub_epi16", feature: "avx2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_hsub_epi32", feature: "avx2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_hsub_pd", feature: "avx", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_hsub_ps", feature: "avx", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_hsubs_epi16", feature: "avx2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_i32gather_epi32", feature: "avx2", arity: 3, imm: &[Imm { index: 2, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm256_i32gather_epi64", feature: "avx2", arity: 3, imm: &[Imm { index: 2, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm256_i32gather_pd", feature: "avx2", arity: 3, imm: &[Imm { index: 2, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm256_i32gather_ps", feature: "avx2", arity: 3, imm: &[Imm { index: 2, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm256_i64gather_epi32", feature: "avx2", arity: 3, imm: &[Imm { index: 2, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm256_i64gather_epi64", feature: "avx2", arity: 3, imm: &[Imm { index: 2, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm256_i64gather_pd", feature: "avx2", arity: 3, imm: &[Imm { index: 2, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm256_i64gather_ps", feature: "avx2", arity: 3, imm: &[Imm { index: 2, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm256_insert_epi16", feature: "avx", arity: 3, imm: &[Imm { index: 2, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm256_insert_epi32", feature: "avx", arity: 3, imm: &[Imm { index: 2, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm256_insert_epi64", feature: "avx", arity: 3, imm: &[Imm { index: 2, rust_ty: "i32" }], x86_64_only: true },
    Intrinsic { name: "_mm256_insert_epi8", feature: "avx", arity: 3, imm: &[Imm { index: 2, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm256_insertf128_pd", feature: "avx", arity: 3, imm: &[Imm { index: 2, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm256_insertf128_ps", feature: "avx", arity: 3, imm: &[Imm { index: 2, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm256_insertf128_si256", feature: "avx", arity: 3, imm: &[Imm { index: 2, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm256_inserti128_si256", feature: "avx2", arity: 3, imm: &[Imm { index: 2, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm256_lddqu_si256", feature: "avx", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_load_pd", feature: "avx", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_load_ps", feature: "avx", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_load_si256", feature: "avx", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_loadu2_m128", feature: "avx", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_loadu2_m128d", feature: "avx", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_loadu2_m128i", feature: "avx", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_loadu_pd", feature: "avx", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_loadu_ps", feature: "avx", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_loadu_si256", feature: "avx", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_madd_epi16", feature: "avx2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_maddubs_epi16", feature: "avx2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_mask_i32gather_epi32", feature: "avx2", arity: 5, imm: &[Imm { index: 4, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm256_mask_i32gather_epi64", feature: "avx2", arity: 5, imm: &[Imm { index: 4, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm256_mask_i32gather_pd", feature: "avx2", arity: 5, imm: &[Imm { index: 4, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm256_mask_i32gather_ps", feature: "avx2", arity: 5, imm: &[Imm { index: 4, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm256_mask_i64gather_epi32", feature: "avx2", arity: 5, imm: &[Imm { index: 4, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm256_mask_i64gather_epi64", feature: "avx2", arity: 5, imm: &[Imm { index: 4, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm256_mask_i64gather_pd", feature: "avx2", arity: 5, imm: &[Imm { index: 4, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm256_mask_i64gather_ps", feature: "avx2", arity: 5, imm: &[Imm { index: 4, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm256_maskload_epi32", feature: "avx2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_maskload_epi64", feature: "avx2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_maskload_pd", feature: "avx", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_maskload_ps", feature: "avx", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_maskstore_epi32", feature: "avx2", arity: 3, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_maskstore_epi64", feature: "avx2", arity: 3, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_maskstore_pd", feature: "avx", arity: 3, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_maskstore_ps", feature: "avx", arity: 3, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_max_epi16", feature: "avx2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_max_epi32", feature: "avx2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_max_epi8", feature: "avx2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_max_epu16", feature: "avx2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_max_epu32", feature: "avx2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_max_epu8", feature: "avx2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_max_pd", feature: "avx", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_max_ps", feature: "avx", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_min_epi16", feature: "avx2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_min_epi32", feature: "avx2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_min_epi8", feature: "avx2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_min_epu16", feature: "avx2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_min_epu32", feature: "avx2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_min_epu8", feature: "avx2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_min_pd", feature: "avx", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_min_ps", feature: "avx", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_movedup_pd", feature: "avx", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_movehdup_ps", feature: "avx", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_moveldup_ps", feature: "avx", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_movemask_epi8", feature: "avx2", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_movemask_pd", feature: "avx", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_movemask_ps", feature: "avx", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_mpsadbw_epu8", feature: "avx2", arity: 3, imm: &[Imm { index: 2, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm256_mul_epi32", feature: "avx2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_mul_epu32", feature: "avx2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_mul_pd", feature: "avx", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_mul_ps", feature: "avx", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_mulhi_epi16", feature: "avx2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_mulhi_epu16", feature: "avx2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_mulhrs_epi16", feature: "avx2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_mullo_epi16", feature: "avx2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_mullo_epi32", feature: "avx2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_or_pd", feature: "avx", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_or_ps", feature: "avx", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_or_si256", feature: "avx2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_packs_epi16", feature: "avx2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_packs_epi32", feature: "avx2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_packus_epi16", feature: "avx2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_packus_epi32", feature: "avx2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_permute2f128_pd", feature: "avx", arity: 3, imm: &[Imm { index: 2, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm256_permute2f128_ps", feature: "avx", arity: 3, imm: &[Imm { index: 2, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm256_permute2f128_si256", feature: "avx", arity: 3, imm: &[Imm { index: 2, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm256_permute2x128_si256", feature: "avx2", arity: 3, imm: &[Imm { index: 2, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm256_permute4x64_epi64", feature: "avx2", arity: 2, imm: &[Imm { index: 1, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm256_permute4x64_pd", feature: "avx2", arity: 2, imm: &[Imm { index: 1, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm256_permute_pd", feature: "avx", arity: 2, imm: &[Imm { index: 1, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm256_permute_ps", feature: "avx", arity: 2, imm: &[Imm { index: 1, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm256_permutevar8x32_epi32", feature: "avx2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_permutevar8x32_ps", feature: "avx2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_permutevar_pd", feature: "avx", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_permutevar_ps", feature: "avx", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_rcp_ps", feature: "avx", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_round_pd", feature: "avx", arity: 2, imm: &[Imm { index: 1, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm256_round_ps", feature: "avx", arity: 2, imm: &[Imm { index: 1, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm256_rsqrt_ps", feature: "avx", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_sad_epu8", feature: "avx2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_set1_epi16", feature: "avx", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_set1_epi32", feature: "avx", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_set1_epi64x", feature: "avx", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_set1_epi8", feature: "avx", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_set1_pd", feature: "avx", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_set1_ps", feature: "avx", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_set_epi16", feature: "avx", arity: 16, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_set_epi32", feature: "avx", arity: 8, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_set_epi64x", feature: "avx", arity: 4, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_set_epi8", feature: "avx", arity: 32, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_set_m128", feature: "avx", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_set_m128d", feature: "avx", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_set_m128i", feature: "avx", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_set_pd", feature: "avx", arity: 4, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_set_ps", feature: "avx", arity: 8, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_setr_epi16", feature: "avx", arity: 16, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_setr_epi32", feature: "avx", arity: 8, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_setr_epi64x", feature: "avx", arity: 4, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_setr_epi8", feature: "avx", arity: 32, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_setr_m128", feature: "avx", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_setr_m128d", feature: "avx", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_setr_m128i", feature: "avx", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_setr_pd", feature: "avx", arity: 4, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_setr_ps", feature: "avx", arity: 8, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_setzero_pd", feature: "avx", arity: 0, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_setzero_ps", feature: "avx", arity: 0, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_setzero_si256", feature: "avx", arity: 0, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_shuffle_epi32", feature: "avx2", arity: 2, imm: &[Imm { index: 1, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm256_shuffle_epi8", feature: "avx2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_shuffle_pd", feature: "avx", arity: 3, imm: &[Imm { index: 2, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm256_shuffle_ps", feature: "avx", arity: 3, imm: &[Imm { index: 2, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm256_shufflehi_epi16", feature: "avx2", arity: 2, imm: &[Imm { index: 1, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm256_shufflelo_epi16", feature: "avx2", arity: 2, imm: &[Imm { index: 1, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm256_sign_epi16", feature: "avx2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_sign_epi32", feature: "avx2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_sign_epi8", feature: "avx2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_sll_epi16", feature: "avx2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_sll_epi32", feature: "avx2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_sll_epi64", feature: "avx2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_slli_epi16", feature: "avx2", arity: 2, imm: &[Imm { index: 1, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm256_slli_epi32", feature: "avx2", arity: 2, imm: &[Imm { index: 1, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm256_slli_epi64", feature: "avx2", arity: 2, imm: &[Imm { index: 1, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm256_slli_si256", feature: "avx2", arity: 2, imm: &[Imm { index: 1, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm256_sllv_epi32", feature: "avx2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_sllv_epi64", feature: "avx2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_sqrt_pd", feature: "avx", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_sqrt_ps", feature: "avx", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_sra_epi16", feature: "avx2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_sra_epi32", feature: "avx2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_srai_epi16", feature: "avx2", arity: 2, imm: &[Imm { index: 1, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm256_srai_epi32", feature: "avx2", arity: 2, imm: &[Imm { index: 1, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm256_srav_epi32", feature: "avx2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_srl_epi16", feature: "avx2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_srl_epi32", feature: "avx2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_srl_epi64", feature: "avx2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_srli_epi16", feature: "avx2", arity: 2, imm: &[Imm { index: 1, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm256_srli_epi32", feature: "avx2", arity: 2, imm: &[Imm { index: 1, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm256_srli_epi64", feature: "avx2", arity: 2, imm: &[Imm { index: 1, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm256_srli_si256", feature: "avx2", arity: 2, imm: &[Imm { index: 1, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm256_srlv_epi32", feature: "avx2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_srlv_epi64", feature: "avx2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_store_pd", feature: "avx", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_store_ps", feature: "avx", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_store_si256", feature: "avx", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_storeu2_m128", feature: "avx", arity: 3, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_storeu2_m128d", feature: "avx", arity: 3, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_storeu2_m128i", feature: "avx", arity: 3, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_storeu_pd", feature: "avx", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_storeu_ps", feature: "avx", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_storeu_si256", feature: "avx", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_stream_load_si256", feature: "avx2", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_stream_pd", feature: "avx", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_stream_ps", feature: "avx", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_stream_si256", feature: "avx", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_sub_epi16", feature: "avx2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_sub_epi32", feature: "avx2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_sub_epi64", feature: "avx2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_sub_epi8", feature: "avx2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_sub_pd", feature: "avx", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_sub_ps", feature: "avx", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_subs_epi16", feature: "avx2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_subs_epi8", feature: "avx2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_subs_epu16", feature: "avx2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_subs_epu8", feature: "avx2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_testc_pd", feature: "avx", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_testc_ps", feature: "avx", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_testc_si256", feature: "avx", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_testnzc_pd", feature: "avx", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_testnzc_ps", feature: "avx", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_testnzc_si256", feature: "avx", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_testz_pd", feature: "avx", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_testz_ps", feature: "avx", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_testz_si256", feature: "avx", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_undefined_pd", feature: "avx", arity: 0, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_undefined_ps", feature: "avx", arity: 0, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_undefined_si256", feature: "avx", arity: 0, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_unpackhi_epi16", feature: "avx2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_unpackhi_epi32", feature: "avx2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_unpackhi_epi64", feature: "avx2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_unpackhi_epi8", feature: "avx2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_unpackhi_pd", feature: "avx", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_unpackhi_ps", feature: "avx", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_unpacklo_epi16", feature: "avx2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_unpacklo_epi32", feature: "avx2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_unpacklo_epi64", feature: "avx2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_unpacklo_epi8", feature: "avx2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_unpacklo_pd", feature: "avx", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_unpacklo_ps", feature: "avx", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_xor_pd", feature: "avx", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_xor_ps", feature: "avx", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_xor_si256", feature: "avx2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_zeroall", feature: "avx", arity: 0, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_zeroupper", feature: "avx", arity: 0, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_zextpd128_pd256", feature: "avx", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_zextps128_ps256", feature: "avx", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm256_zextsi128_si256", feature: "avx", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_abs_epi16", feature: "ssse3", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_abs_epi32", feature: "ssse3", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_abs_epi8", feature: "ssse3", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_add_epi16", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_add_epi32", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_add_epi64", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_add_epi8", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_add_pd", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_add_ps", feature: "sse", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_add_sd", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_add_ss", feature: "sse", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_adds_epi16", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_adds_epi8", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_adds_epu16", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_adds_epu8", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_addsub_pd", feature: "sse3", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_addsub_ps", feature: "sse3", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_aesdec_si128", feature: "aes", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_aesdeclast_si128", feature: "aes", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_aesenc_si128", feature: "aes", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_aesenclast_si128", feature: "aes", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_aesimc_si128", feature: "aes", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_aeskeygenassist_si128", feature: "aes", arity: 2, imm: &[Imm { index: 1, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm_alignr_epi8", feature: "ssse3", arity: 3, imm: &[Imm { index: 2, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm_and_pd", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_and_ps", feature: "sse", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_and_si128", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_andnot_pd", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_andnot_ps", feature: "sse", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_andnot_si128", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_avg_epu16", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_avg_epu8", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_blend_epi16", feature: "sse4.1", arity: 3, imm: &[Imm { index: 2, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm_blend_epi32", feature: "avx2", arity: 3, imm: &[Imm { index: 2, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm_blend_pd", feature: "sse4.1", arity: 3, imm: &[Imm { index: 2, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm_blend_ps", feature: "sse4.1", arity: 3, imm: &[Imm { index: 2, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm_blendv_epi8", feature: "sse4.1", arity: 3, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_blendv_pd", feature: "sse4.1", arity: 3, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_blendv_ps", feature: "sse4.1", arity: 3, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_broadcastb_epi8", feature: "avx2", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_broadcastd_epi32", feature: "avx2", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_broadcastq_epi64", feature: "avx2", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_broadcastsd_pd", feature: "avx2", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_broadcastsi128_si256", feature: "avx2", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_broadcastss_ps", feature: "avx2", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_broadcastw_epi16", feature: "avx2", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_bslli_si128", feature: "sse2", arity: 2, imm: &[Imm { index: 1, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm_bsrli_si128", feature: "sse2", arity: 2, imm: &[Imm { index: 1, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm_castpd_ps", feature: "sse2", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_castpd_si128", feature: "sse2", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_castps_pd", feature: "sse2", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_castps_si128", feature: "sse2", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_castsi128_pd", feature: "sse2", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_castsi128_ps", feature: "sse2", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_ceil_pd", feature: "sse4.1", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_ceil_ps", feature: "sse4.1", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_ceil_sd", feature: "sse4.1", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_ceil_ss", feature: "sse4.1", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_clflush", feature: "sse2", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_clmulepi64_si128", feature: "pclmulqdq", arity: 3, imm: &[Imm { index: 2, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm_cmp_pd", feature: "avx", arity: 3, imm: &[Imm { index: 2, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm_cmp_ps", feature: "avx", arity: 3, imm: &[Imm { index: 2, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm_cmp_sd", feature: "avx", arity: 3, imm: &[Imm { index: 2, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm_cmp_ss", feature: "avx", arity: 3, imm: &[Imm { index: 2, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm_cmpeq_epi16", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_cmpeq_epi32", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_cmpeq_epi64", feature: "sse4.1", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_cmpeq_epi8", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_cmpeq_pd", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_cmpeq_ps", feature: "sse", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_cmpeq_sd", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_cmpeq_ss", feature: "sse", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_cmpestra", feature: "sse4.2", arity: 5, imm: &[Imm { index: 4, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm_cmpestrc", feature: "sse4.2", arity: 5, imm: &[Imm { index: 4, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm_cmpestri", feature: "sse4.2", arity: 5, imm: &[Imm { index: 4, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm_cmpestrm", feature: "sse4.2", arity: 5, imm: &[Imm { index: 4, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm_cmpestro", feature: "sse4.2", arity: 5, imm: &[Imm { index: 4, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm_cmpestrs", feature: "sse4.2", arity: 5, imm: &[Imm { index: 4, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm_cmpestrz", feature: "sse4.2", arity: 5, imm: &[Imm { index: 4, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm_cmpge_pd", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_cmpge_ps", feature: "sse", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_cmpge_sd", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_cmpge_ss", feature: "sse", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_cmpgt_epi16", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_cmpgt_epi32", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_cmpgt_epi64", feature: "sse4.2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_cmpgt_epi8", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_cmpgt_pd", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_cmpgt_ps", feature: "sse", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_cmpgt_sd", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_cmpgt_ss", feature: "sse", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_cmpistra", feature: "sse4.2", arity: 3, imm: &[Imm { index: 2, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm_cmpistrc", feature: "sse4.2", arity: 3, imm: &[Imm { index: 2, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm_cmpistri", feature: "sse4.2", arity: 3, imm: &[Imm { index: 2, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm_cmpistrm", feature: "sse4.2", arity: 3, imm: &[Imm { index: 2, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm_cmpistro", feature: "sse4.2", arity: 3, imm: &[Imm { index: 2, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm_cmpistrs", feature: "sse4.2", arity: 3, imm: &[Imm { index: 2, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm_cmpistrz", feature: "sse4.2", arity: 3, imm: &[Imm { index: 2, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm_cmple_pd", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_cmple_ps", feature: "sse", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_cmple_sd", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_cmple_ss", feature: "sse", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_cmplt_epi16", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_cmplt_epi32", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_cmplt_epi8", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_cmplt_pd", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_cmplt_ps", feature: "sse", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_cmplt_sd", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_cmplt_ss", feature: "sse", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_cmpneq_pd", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_cmpneq_ps", feature: "sse", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_cmpneq_sd", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_cmpneq_ss", feature: "sse", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_cmpnge_pd", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_cmpnge_ps", feature: "sse", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_cmpnge_sd", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_cmpnge_ss", feature: "sse", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_cmpngt_pd", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_cmpngt_ps", feature: "sse", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_cmpngt_sd", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_cmpngt_ss", feature: "sse", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_cmpnle_pd", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_cmpnle_ps", feature: "sse", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_cmpnle_sd", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_cmpnle_ss", feature: "sse", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_cmpnlt_pd", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_cmpnlt_ps", feature: "sse", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_cmpnlt_sd", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_cmpnlt_ss", feature: "sse", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_cmpord_pd", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_cmpord_ps", feature: "sse", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_cmpord_sd", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_cmpord_ss", feature: "sse", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_cmpunord_pd", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_cmpunord_ps", feature: "sse", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_cmpunord_sd", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_cmpunord_ss", feature: "sse", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_comieq_sd", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_comieq_ss", feature: "sse", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_comige_sd", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_comige_ss", feature: "sse", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_comigt_sd", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_comigt_ss", feature: "sse", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_comile_sd", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_comile_ss", feature: "sse", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_comilt_sd", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_comilt_ss", feature: "sse", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_comineq_sd", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_comineq_ss", feature: "sse", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_crc32_u16", feature: "sse4.2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_crc32_u32", feature: "sse4.2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_crc32_u64", feature: "sse4.2", arity: 2, imm: &[], x86_64_only: true },
    Intrinsic { name: "_mm_crc32_u8", feature: "sse4.2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_cvt_si2ss", feature: "sse", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_cvt_ss2si", feature: "sse", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_cvtepi16_epi32", feature: "sse4.1", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_cvtepi16_epi64", feature: "sse4.1", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_cvtepi32_epi64", feature: "sse4.1", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_cvtepi32_pd", feature: "sse2", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_cvtepi32_ps", feature: "sse2", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_cvtepi8_epi16", feature: "sse4.1", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_cvtepi8_epi32", feature: "sse4.1", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_cvtepi8_epi64", feature: "sse4.1", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_cvtepu16_epi32", feature: "sse4.1", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_cvtepu16_epi64", feature: "sse4.1", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_cvtepu32_epi64", feature: "sse4.1", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_cvtepu8_epi16", feature: "sse4.1", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_cvtepu8_epi32", feature: "sse4.1", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_cvtepu8_epi64", feature: "sse4.1", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_cvtpd_epi32", feature: "sse2", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_cvtpd_ps", feature: "sse2", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_cvtps_epi32", feature: "sse2", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_cvtps_pd", feature: "sse2", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_cvtsd_f64", feature: "sse2", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_cvtsd_si32", feature: "sse2", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_cvtsd_si64", feature: "sse2", arity: 1, imm: &[], x86_64_only: true },
    Intrinsic { name: "_mm_cvtsd_si64x", feature: "sse2", arity: 1, imm: &[], x86_64_only: true },
    Intrinsic { name: "_mm_cvtsd_ss", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_cvtsi128_si32", feature: "sse2", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_cvtsi128_si64", feature: "sse2", arity: 1, imm: &[], x86_64_only: true },
    Intrinsic { name: "_mm_cvtsi128_si64x", feature: "sse2", arity: 1, imm: &[], x86_64_only: true },
    Intrinsic { name: "_mm_cvtsi32_sd", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_cvtsi32_si128", feature: "sse2", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_cvtsi32_ss", feature: "sse", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_cvtsi64_sd", feature: "sse2", arity: 2, imm: &[], x86_64_only: true },
    Intrinsic { name: "_mm_cvtsi64_si128", feature: "sse2", arity: 1, imm: &[], x86_64_only: true },
    Intrinsic { name: "_mm_cvtsi64_ss", feature: "sse", arity: 2, imm: &[], x86_64_only: true },
    Intrinsic { name: "_mm_cvtsi64x_sd", feature: "sse2", arity: 2, imm: &[], x86_64_only: true },
    Intrinsic { name: "_mm_cvtsi64x_si128", feature: "sse2", arity: 1, imm: &[], x86_64_only: true },
    Intrinsic { name: "_mm_cvtss_f32", feature: "sse", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_cvtss_sd", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_cvtss_si32", feature: "sse", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_cvtss_si64", feature: "sse", arity: 1, imm: &[], x86_64_only: true },
    Intrinsic { name: "_mm_cvtt_ss2si", feature: "sse", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_cvttpd_epi32", feature: "sse2", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_cvttps_epi32", feature: "sse2", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_cvttsd_si32", feature: "sse2", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_cvttsd_si64", feature: "sse2", arity: 1, imm: &[], x86_64_only: true },
    Intrinsic { name: "_mm_cvttsd_si64x", feature: "sse2", arity: 1, imm: &[], x86_64_only: true },
    Intrinsic { name: "_mm_cvttss_si32", feature: "sse", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_cvttss_si64", feature: "sse", arity: 1, imm: &[], x86_64_only: true },
    Intrinsic { name: "_mm_div_pd", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_div_ps", feature: "sse", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_div_sd", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_div_ss", feature: "sse", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_dp_pd", feature: "sse4.1", arity: 3, imm: &[Imm { index: 2, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm_dp_ps", feature: "sse4.1", arity: 3, imm: &[Imm { index: 2, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm_extract_epi16", feature: "sse2", arity: 2, imm: &[Imm { index: 1, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm_extract_epi32", feature: "sse4.1", arity: 2, imm: &[Imm { index: 1, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm_extract_epi64", feature: "sse4.1", arity: 2, imm: &[Imm { index: 1, rust_ty: "i32" }], x86_64_only: true },
    Intrinsic { name: "_mm_extract_epi8", feature: "sse4.1", arity: 2, imm: &[Imm { index: 1, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm_extract_ps", feature: "sse4.1", arity: 2, imm: &[Imm { index: 1, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm_floor_pd", feature: "sse4.1", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_floor_ps", feature: "sse4.1", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_floor_sd", feature: "sse4.1", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_floor_ss", feature: "sse4.1", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_fmadd_pd", feature: "fma", arity: 3, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_fmadd_ps", feature: "fma", arity: 3, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_fmadd_sd", feature: "fma", arity: 3, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_fmadd_ss", feature: "fma", arity: 3, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_fmaddsub_pd", feature: "fma", arity: 3, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_fmaddsub_ps", feature: "fma", arity: 3, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_fmsub_pd", feature: "fma", arity: 3, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_fmsub_ps", feature: "fma", arity: 3, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_fmsub_sd", feature: "fma", arity: 3, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_fmsub_ss", feature: "fma", arity: 3, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_fmsubadd_pd", feature: "fma", arity: 3, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_fmsubadd_ps", feature: "fma", arity: 3, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_fnmadd_pd", feature: "fma", arity: 3, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_fnmadd_ps", feature: "fma", arity: 3, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_fnmadd_sd", feature: "fma", arity: 3, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_fnmadd_ss", feature: "fma", arity: 3, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_fnmsub_pd", feature: "fma", arity: 3, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_fnmsub_ps", feature: "fma", arity: 3, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_fnmsub_sd", feature: "fma", arity: 3, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_fnmsub_ss", feature: "fma", arity: 3, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_hadd_epi16", feature: "ssse3", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_hadd_epi32", feature: "ssse3", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_hadd_pd", feature: "sse3", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_hadd_ps", feature: "sse3", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_hadds_epi16", feature: "ssse3", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_hsub_epi16", feature: "ssse3", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_hsub_epi32", feature: "ssse3", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_hsub_pd", feature: "sse3", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_hsub_ps", feature: "sse3", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_hsubs_epi16", feature: "ssse3", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_i32gather_epi32", feature: "avx2", arity: 3, imm: &[Imm { index: 2, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm_i32gather_epi64", feature: "avx2", arity: 3, imm: &[Imm { index: 2, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm_i32gather_pd", feature: "avx2", arity: 3, imm: &[Imm { index: 2, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm_i32gather_ps", feature: "avx2", arity: 3, imm: &[Imm { index: 2, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm_i64gather_epi32", feature: "avx2", arity: 3, imm: &[Imm { index: 2, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm_i64gather_epi64", feature: "avx2", arity: 3, imm: &[Imm { index: 2, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm_i64gather_pd", feature: "avx2", arity: 3, imm: &[Imm { index: 2, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm_i64gather_ps", feature: "avx2", arity: 3, imm: &[Imm { index: 2, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm_insert_epi16", feature: "sse2", arity: 3, imm: &[Imm { index: 2, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm_insert_epi32", feature: "sse4.1", arity: 3, imm: &[Imm { index: 2, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm_insert_epi64", feature: "sse4.1", arity: 3, imm: &[Imm { index: 2, rust_ty: "i32" }], x86_64_only: true },
    Intrinsic { name: "_mm_insert_epi8", feature: "sse4.1", arity: 3, imm: &[Imm { index: 2, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm_insert_ps", feature: "sse4.1", arity: 3, imm: &[Imm { index: 2, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm_lddqu_si128", feature: "sse3", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_lfence", feature: "sse2", arity: 0, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_load1_pd", feature: "sse2", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_load1_ps", feature: "sse", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_load_pd", feature: "sse2", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_load_pd1", feature: "sse2", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_load_ps", feature: "sse", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_load_ps1", feature: "sse", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_load_sd", feature: "sse2", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_load_si128", feature: "sse2", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_load_ss", feature: "sse", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_loaddup_pd", feature: "sse3", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_loadh_pd", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_loadl_epi64", feature: "sse2", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_loadl_pd", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_loadr_pd", feature: "sse2", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_loadr_ps", feature: "sse", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_loadu_pd", feature: "sse2", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_loadu_ps", feature: "sse", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_loadu_si128", feature: "sse2", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_loadu_si16", feature: "sse2", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_loadu_si32", feature: "sse2", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_loadu_si64", feature: "sse2", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_madd_epi16", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_maddubs_epi16", feature: "ssse3", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_mask_i32gather_epi32", feature: "avx2", arity: 5, imm: &[Imm { index: 4, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm_mask_i32gather_epi64", feature: "avx2", arity: 5, imm: &[Imm { index: 4, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm_mask_i32gather_pd", feature: "avx2", arity: 5, imm: &[Imm { index: 4, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm_mask_i32gather_ps", feature: "avx2", arity: 5, imm: &[Imm { index: 4, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm_mask_i64gather_epi32", feature: "avx2", arity: 5, imm: &[Imm { index: 4, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm_mask_i64gather_epi64", feature: "avx2", arity: 5, imm: &[Imm { index: 4, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm_mask_i64gather_pd", feature: "avx2", arity: 5, imm: &[Imm { index: 4, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm_mask_i64gather_ps", feature: "avx2", arity: 5, imm: &[Imm { index: 4, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm_maskload_epi32", feature: "avx2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_maskload_epi64", feature: "avx2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_maskload_pd", feature: "avx", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_maskload_ps", feature: "avx", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_maskmoveu_si128", feature: "sse2", arity: 3, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_maskstore_epi32", feature: "avx2", arity: 3, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_maskstore_epi64", feature: "avx2", arity: 3, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_maskstore_pd", feature: "avx", arity: 3, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_maskstore_ps", feature: "avx", arity: 3, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_max_epi16", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_max_epi32", feature: "sse4.1", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_max_epi8", feature: "sse4.1", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_max_epu16", feature: "sse4.1", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_max_epu32", feature: "sse4.1", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_max_epu8", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_max_pd", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_max_ps", feature: "sse", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_max_sd", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_max_ss", feature: "sse", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_mfence", feature: "sse2", arity: 0, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_min_epi16", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_min_epi32", feature: "sse4.1", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_min_epi8", feature: "sse4.1", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_min_epu16", feature: "sse4.1", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_min_epu32", feature: "sse4.1", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_min_epu8", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_min_pd", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_min_ps", feature: "sse", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_min_sd", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_min_ss", feature: "sse", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_minpos_epu16", feature: "sse4.1", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_move_epi64", feature: "sse2", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_move_sd", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_move_ss", feature: "sse", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_movedup_pd", feature: "sse3", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_movehdup_ps", feature: "sse3", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_movehl_ps", feature: "sse", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_moveldup_ps", feature: "sse3", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_movelh_ps", feature: "sse", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_movemask_epi8", feature: "sse2", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_movemask_pd", feature: "sse2", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_movemask_ps", feature: "sse", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_mpsadbw_epu8", feature: "sse4.1", arity: 3, imm: &[Imm { index: 2, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm_mul_epi32", feature: "sse4.1", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_mul_epu32", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_mul_pd", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_mul_ps", feature: "sse", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_mul_sd", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_mul_ss", feature: "sse", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_mulhi_epi16", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_mulhi_epu16", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_mulhrs_epi16", feature: "ssse3", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_mullo_epi16", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_mullo_epi32", feature: "sse4.1", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_or_pd", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_or_ps", feature: "sse", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_or_si128", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_packs_epi16", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_packs_epi32", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_packus_epi16", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_packus_epi32", feature: "sse4.1", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_pause", feature: "", arity: 0, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_permute_pd", feature: "avx", arity: 2, imm: &[Imm { index: 1, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm_permute_ps", feature: "avx", arity: 2, imm: &[Imm { index: 1, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm_permutevar_pd", feature: "avx", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_permutevar_ps", feature: "avx", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_prefetch", feature: "sse", arity: 2, imm: &[Imm { index: 1, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm_rcp_ps", feature: "sse", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_rcp_ss", feature: "sse", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_round_pd", feature: "sse4.1", arity: 2, imm: &[Imm { index: 1, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm_round_ps", feature: "sse4.1", arity: 2, imm: &[Imm { index: 1, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm_round_sd", feature: "sse4.1", arity: 3, imm: &[Imm { index: 2, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm_round_ss", feature: "sse4.1", arity: 3, imm: &[Imm { index: 2, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm_rsqrt_ps", feature: "sse", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_rsqrt_ss", feature: "sse", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_sad_epu8", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_set1_epi16", feature: "sse2", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_set1_epi32", feature: "sse2", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_set1_epi64x", feature: "sse2", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_set1_epi8", feature: "sse2", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_set1_pd", feature: "sse2", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_set1_ps", feature: "sse", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_set_epi16", feature: "sse2", arity: 8, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_set_epi32", feature: "sse2", arity: 4, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_set_epi64x", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_set_epi8", feature: "sse2", arity: 16, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_set_pd", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_set_pd1", feature: "sse2", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_set_ps", feature: "sse", arity: 4, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_set_ps1", feature: "sse", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_set_sd", feature: "sse2", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_set_ss", feature: "sse", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_setr_epi16", feature: "sse2", arity: 8, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_setr_epi32", feature: "sse2", arity: 4, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_setr_epi8", feature: "sse2", arity: 16, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_setr_pd", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_setr_ps", feature: "sse", arity: 4, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_setzero_pd", feature: "sse2", arity: 0, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_setzero_ps", feature: "sse", arity: 0, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_setzero_si128", feature: "sse2", arity: 0, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_sfence", feature: "sse", arity: 0, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_sha1msg1_epu32", feature: "sha", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_sha1msg2_epu32", feature: "sha", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_sha1nexte_epu32", feature: "sha", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_sha1rnds4_epu32", feature: "sha", arity: 3, imm: &[Imm { index: 2, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm_sha256msg1_epu32", feature: "sha", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_sha256msg2_epu32", feature: "sha", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_sha256rnds2_epu32", feature: "sha", arity: 3, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_shuffle_epi32", feature: "sse2", arity: 2, imm: &[Imm { index: 1, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm_shuffle_epi8", feature: "ssse3", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_shuffle_pd", feature: "sse2", arity: 3, imm: &[Imm { index: 2, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm_shuffle_ps", feature: "sse", arity: 3, imm: &[Imm { index: 2, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm_shufflehi_epi16", feature: "sse2", arity: 2, imm: &[Imm { index: 1, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm_shufflelo_epi16", feature: "sse2", arity: 2, imm: &[Imm { index: 1, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm_sign_epi16", feature: "ssse3", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_sign_epi32", feature: "ssse3", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_sign_epi8", feature: "ssse3", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_sll_epi16", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_sll_epi32", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_sll_epi64", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_slli_epi16", feature: "sse2", arity: 2, imm: &[Imm { index: 1, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm_slli_epi32", feature: "sse2", arity: 2, imm: &[Imm { index: 1, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm_slli_epi64", feature: "sse2", arity: 2, imm: &[Imm { index: 1, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm_slli_si128", feature: "sse2", arity: 2, imm: &[Imm { index: 1, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm_sllv_epi32", feature: "avx2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_sllv_epi64", feature: "avx2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_sqrt_pd", feature: "sse2", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_sqrt_ps", feature: "sse", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_sqrt_sd", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_sqrt_ss", feature: "sse", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_sra_epi16", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_sra_epi32", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_srai_epi16", feature: "sse2", arity: 2, imm: &[Imm { index: 1, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm_srai_epi32", feature: "sse2", arity: 2, imm: &[Imm { index: 1, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm_srav_epi32", feature: "avx2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_srl_epi16", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_srl_epi32", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_srl_epi64", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_srli_epi16", feature: "sse2", arity: 2, imm: &[Imm { index: 1, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm_srli_epi32", feature: "sse2", arity: 2, imm: &[Imm { index: 1, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm_srli_epi64", feature: "sse2", arity: 2, imm: &[Imm { index: 1, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm_srli_si128", feature: "sse2", arity: 2, imm: &[Imm { index: 1, rust_ty: "i32" }], x86_64_only: false },
    Intrinsic { name: "_mm_srlv_epi32", feature: "avx2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_srlv_epi64", feature: "avx2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_store1_pd", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_store1_ps", feature: "sse", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_store_pd", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_store_pd1", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_store_ps", feature: "sse", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_store_ps1", feature: "sse", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_store_sd", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_store_si128", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_store_ss", feature: "sse", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_storeh_pd", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_storel_epi64", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_storel_pd", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_storer_pd", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_storer_ps", feature: "sse", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_storeu_pd", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_storeu_ps", feature: "sse", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_storeu_si128", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_storeu_si16", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_storeu_si32", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_storeu_si64", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_stream_load_si128", feature: "sse4.1", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_stream_pd", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_stream_ps", feature: "sse", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_stream_si128", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_stream_si32", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_stream_si64", feature: "sse2", arity: 2, imm: &[], x86_64_only: true },
    Intrinsic { name: "_mm_sub_epi16", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_sub_epi32", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_sub_epi64", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_sub_epi8", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_sub_pd", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_sub_ps", feature: "sse", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_sub_sd", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_sub_ss", feature: "sse", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_subs_epi16", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_subs_epi8", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_subs_epu16", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_subs_epu8", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_test_all_ones", feature: "sse4.1", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_test_all_zeros", feature: "sse4.1", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_test_mix_ones_zeros", feature: "sse4.1", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_testc_pd", feature: "avx", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_testc_ps", feature: "avx", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_testc_si128", feature: "sse4.1", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_testnzc_pd", feature: "avx", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_testnzc_ps", feature: "avx", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_testnzc_si128", feature: "sse4.1", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_testz_pd", feature: "avx", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_testz_ps", feature: "avx", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_testz_si128", feature: "sse4.1", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_tzcnt_32", feature: "bmi1", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_tzcnt_64", feature: "bmi1", arity: 1, imm: &[], x86_64_only: true },
    Intrinsic { name: "_mm_ucomieq_sd", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_ucomieq_ss", feature: "sse", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_ucomige_sd", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_ucomige_ss", feature: "sse", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_ucomigt_sd", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_ucomigt_ss", feature: "sse", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_ucomile_sd", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_ucomile_ss", feature: "sse", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_ucomilt_sd", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_ucomilt_ss", feature: "sse", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_ucomineq_sd", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_ucomineq_ss", feature: "sse", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_undefined_pd", feature: "sse2", arity: 0, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_undefined_ps", feature: "sse", arity: 0, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_undefined_si128", feature: "sse2", arity: 0, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_unpackhi_epi16", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_unpackhi_epi32", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_unpackhi_epi64", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_unpackhi_epi8", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_unpackhi_pd", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_unpackhi_ps", feature: "sse", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_unpacklo_epi16", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_unpacklo_epi32", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_unpacklo_epi64", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_unpacklo_epi8", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_unpacklo_pd", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_unpacklo_ps", feature: "sse", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_xor_pd", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_xor_ps", feature: "sse", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_mm_xor_si128", feature: "sse2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_pdep_u32", feature: "bmi2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_pdep_u64", feature: "bmi2", arity: 2, imm: &[], x86_64_only: true },
    Intrinsic { name: "_pext_u32", feature: "bmi2", arity: 2, imm: &[], x86_64_only: false },
    Intrinsic { name: "_pext_u64", feature: "bmi2", arity: 2, imm: &[], x86_64_only: true },
    Intrinsic { name: "_popcnt32", feature: "popcnt", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_popcnt64", feature: "popcnt", arity: 1, imm: &[], x86_64_only: true },
    Intrinsic { name: "_tzcnt_u16", feature: "bmi1", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_tzcnt_u32", feature: "bmi1", arity: 1, imm: &[], x86_64_only: false },
    Intrinsic { name: "_tzcnt_u64", feature: "bmi1", arity: 1, imm: &[], x86_64_only: true },
];
