/* A LINPACK-style dense linear solve: LU decomposition with partial pivoting,
 * then a triangular solve, then the residual.
 *
 * NOT the netlib program. `netlib.org/benchmark/linpackc.new` — the C
 * translation by Bonnie Toy, later modified by Will Menninger and Jack
 * Dongarra — carries no licence notice at all, and it reports MFLOPS, which
 * is a different number on every run and so cannot be compared byte for byte
 * across three builds the way this suite compares everything else. So the
 * kernel is written out here instead, from the published structure of the
 * benchmark: `idamax`, `dscal`, `daxpy`, `dgefa`, `dgesl`, a right-hand side
 * chosen so that the answer is all ones, and the residual printed rather than
 * a rate. The arithmetic performed is the same as the benchmark's — the same
 * O(n^3/3) of `daxpy` over columns — and the matrix is generated by a fixed
 * LCG so the result is the same on every machine.
 *
 * SPDX-License-Identifier: MIT OR Apache-2.0
 */

#include <math.h>
#include <stdio.h>
#include <stdlib.h>

/* Column-major, as LINPACK is: a[i + j * lda]. */

static int idamax(int n, const double *dx, int incx) {
    double dmax;
    int i, ix, index = 0;
    if (n < 1) return -1;
    if (n == 1) return 0;
    ix = 0;
    dmax = fabs(dx[0]);
    ix += incx;
    for (i = 1; i < n; i++) {
        double v = fabs(dx[ix]);
        if (v > dmax) {
            index = i;
            dmax = v;
        }
        ix += incx;
    }
    return index;
}

static void dscal(int n, double da, double *dx, int incx) {
    int i, ix = 0;
    for (i = 0; i < n; i++) {
        dx[ix] *= da;
        ix += incx;
    }
}

static void daxpy(int n, double da, const double *dx, int incx, double *dy, int incy) {
    int i, ix = 0, iy = 0;
    if (da == 0.0) return;
    if (incx == 1 && incy == 1) {
        for (i = 0; i < n; i++) dy[i] += da * dx[i];
        return;
    }
    for (i = 0; i < n; i++) {
        dy[iy] += da * dx[ix];
        ix += incx;
        iy += incy;
    }
}

/* LU with partial pivoting; `ipvt` records the pivot rows. Returns the index
 * of the first exactly-zero pivot, or -1. */
static int dgefa(double *a, int lda, int n, int *ipvt) {
    int info = -1;
    int j, k;

    for (k = 0; k < n - 1; k++) {
        double *col_k = a + k * lda;
        int l = idamax(n - k, col_k + k, 1) + k;
        ipvt[k] = l;

        if (col_k[l] == 0.0) {
            info = k;
            continue;
        }
        if (l != k) {
            double t = col_k[l];
            col_k[l] = col_k[k];
            col_k[k] = t;
        }
        dscal(n - k - 1, -1.0 / col_k[k], col_k + k + 1, 1);

        for (j = k + 1; j < n; j++) {
            double *col_j = a + j * lda;
            double t = col_j[l];
            if (l != k) {
                col_j[l] = col_j[k];
                col_j[k] = t;
            }
            daxpy(n - k - 1, t, col_k + k + 1, 1, col_j + k + 1, 1);
        }
    }
    ipvt[n - 1] = n - 1;
    if (a[(n - 1) + (n - 1) * lda] == 0.0) info = n - 1;
    return info;
}

/* Solve A x = b using the factorisation dgefa left behind. */
static void dgesl(const double *a, int lda, int n, const int *ipvt, double *b) {
    int k, l;

    for (k = 0; k < n - 1; k++) {
        double t;
        l = ipvt[k];
        t = b[l];
        if (l != k) {
            b[l] = b[k];
            b[k] = t;
        }
        daxpy(n - k - 1, t, a + k * lda + k + 1, 1, b + k + 1, 1);
    }
    for (k = n - 1; k >= 0; k--) {
        b[k] /= a[k + k * lda];
        daxpy(k, -b[k], a + k * lda, 1, b, 1);
    }
}

int main(int argc, char **argv) {
    int n = (argc > 1) ? atoi(argv[1]) : 1000;
    int reps = (argc > 2) ? atoi(argv[2]) : 1;
    int lda = n;
    double *a = malloc((size_t) lda * n * sizeof(double));
    double *keep = malloc((size_t) lda * n * sizeof(double));
    double *b = malloc((size_t) n * sizeof(double));
    int *ipvt = malloc((size_t) n * sizeof(int));
    unsigned state = 1325u;
    double resid = 0.0, normx = 0.0;
    int i, j, r;

    if (!a || !keep || !b || !ipvt) {
        fprintf(stderr, "linpack: out of memory\n");
        return 1;
    }

    for (j = 0; j < n; j++) {
        for (i = 0; i < n; i++) {
            state = state * 1664525u + 1013904223u;
            keep[i + j * lda] = (double) (state >> 8) / 16777216.0 - 0.5;
        }
        keep[j + j * lda] += (double) n / 4.0; /* diagonally dominant enough to be stable */
    }

    for (r = 0; r < reps; r++) {
        for (i = 0; i < lda * n; i++) a[i] = keep[i];
        /* b = A * ones, so the solution is the vector of ones */
        for (i = 0; i < n; i++) {
            double s = 0.0;
            for (j = 0; j < n; j++) s += keep[i + j * lda];
            b[i] = s;
        }
        dgefa(a, lda, n, ipvt);
        dgesl(a, lda, n, ipvt, b);
    }

    for (i = 0; i < n; i++) {
        double e = fabs(b[i] - 1.0);
        if (e > resid) resid = e;
        normx += fabs(b[i]);
    }

    printf("linpack n=%d reps=%d resid=%.3e normx=%.9f\n", n, reps, resid, normx);
    free(a);
    free(keep);
    free(b);
    free(ipvt);
    return 0;
}
